const path = require("path");
const fs = require("fs");
const esbuild = require("esbuild");

// Bundles lib/cm6/entry.js (CodeMirror 6 + this package's own wrapper +
// asset-path completion source) into one static IIFE file, served to the
// admin UI as a plain <script> by lib/asset-plugin.js — see that file's
// "_cm6-editor.js" route. asset-function.html and lib/asset-plugin.html's
// calc-script dialog both call into window.KufayekaCM6.* rather than
// RED.editor.createEditor (ace/monaco); see lib/cm6/cm6-code-editor.js for
// why. dist/ is gitignored (like node-red-nexa-dashboard's own dist/) — run
// `npm run build` after checkout / before first use.
const isWatch = process.argv.includes("--watch");
const entry = path.join(__dirname, "lib", "cm6", "entry.js");
const outBundle = path.join(__dirname, "dist", "asset-engine-cm6.bundle.js");

async function runBuild() {
    const startTime = Date.now();
    try {
        const result = await esbuild.build({
            entryPoints: [entry],
            bundle: true,
            format: "iife",
            globalName: "KufayekaCM6",
            write: false,
            target: ["es2020"]
        });

        const distDir = path.join(__dirname, "dist");
        if (!fs.existsSync(distDir)) fs.mkdirSync(distDir, { recursive: true });

        const banner = "// AUTO-GENERATED by build.js from lib/cm6/entry.js — DO NOT EDIT THIS FILE.\n" +
            "// Edit the modular source files under lib/cm6/ instead, then run\n" +
            "// `npm run build` (or `npm run watch`). Served by lib/asset-plugin.js.\n";
        fs.writeFileSync(outBundle, banner + result.outputFiles[0].text, "utf8");

        console.log(`[build] Built asset-engine-cm6.bundle.js in ${Date.now() - startTime}ms`);
    } catch (e) {
        console.error("[build] Build error:", e);
    }
}

if (isWatch) {
    runBuild().then(() => {
        console.log("[build] Watching lib/cm6/ for changes...");
        fs.watch(path.join(__dirname, "lib", "cm6"), { recursive: true }, () => runBuild());
    });
} else {
    runBuild();
}
